[project]
name = "latent-diffusion-playground"
version = "0.1.0"
description = "Interactive Visualization of VAE, DDPM and U-Net"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0.0",
    "torchvision",
    "numpy",
    "pandas",
    "pillow",
    "pyyaml",
    "pyarrow",
    "tqdm",
    "matplotlib",
    "scipy",
]

[project.optional-dependencies]
train = [
    "accelerate",
    "tensorboard",
    "lpips",
]
gui = [
    "streamlit",
    "plotly",
]